### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.4:generate (default-cli) on project standalone-pom: The desired archetype does not exist (com.airhacks:jakartaee-essentials-archetype:0.0.1)

### ISSUE THREAD

**Issue by sharpedavid** [AdamBien/JakartaEE-essentials-archetype#1]
This archetype isn't working for me. I'm using Apache Maven 3.3.9 on Windows 10, running maven from the standard Windows `cmd`.

One of your other archetypes, `mvn archetype:generate -Dfilter=com.airhacks:javaee8-essentials-archetype`, is working fine.

```
C:\Users\David\Documents\NetBeansProjects>mvn archetype:generate -DarchetypeGroupId=com.airhacks -DarchetypeArtifactId=jakartaee-essentials-archetype -DarchetypeVersion=0.0.1
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> maven-archetype-plugin:2.4:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO]
[INFO] <<< maven-archetype-plugin:2.4:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO]
[INFO] --- maven-archetype-plugin:2.4:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Interactive mode
[INFO] Archetype repository not defined. Using the one from [com.airhacks:jakartaee-essentials-archetype:0.0.2] found in catalog remote
Downloading: https://repo.maven.apache.org/maven2/com/airhacks/jakartaee-essentials-archetype/0.0.1/jakartaee-essentials-archetype-0.0.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.143 s
[INFO] Finished at: 2019-12-08T13:45:50-08:00
[INFO] Final Memory: 15M/192M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.4:generate (default-cli) on project standalone-pom: The desired archetype does not exist (com.airhacks:jakartaee-essentials-archetype:0.0.1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by Bukama** [comment]
There is no archtetype in verison `0.0.1` in the maven central as you can see [maven-central: JakartaEE Essentials Archetype](https://mvnrepository.com/artifact/com.airhacks/jakartaee-essentials-archetype)

_Note_: As of now (2020-01-05 19:52) the freshly deployed version 0.0.3 isn't shown too, but it works while generating it

`[INFO] --- maven-archetype-plugin:3.1.2:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Batch mode
[INFO] Archetype repository not defined. Using the one from [com.airhacks:jakartaee-essentials-archetype:0.0.3] found in catalog remote
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/airhacks/jakartaee-essentials-archetype/0.0.3/jakartaee-essentials-archetype-0.0.3.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/airhacks/jakartaee-essentials-archetype/0.0.3/jakartaee-essentials-archetype-0.0.3.pom (3.9 kB at 14 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/airhacks/jakartaee-essentials-archetype/0.0.3/jakartaee-essentials-archetype-0.0.3.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/airhacks/jakartaee-essentials-archetype/0.0.3/jakartaee-essentials-archetype-0.0.3.jar (4.0 kB at 13 kB/s)
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: jakartaee-essentials-archetype:0.0.3
[INFO] ----------------------------------------------------------------------------`
